name: Publish

on:
  release:
    types: [created]

jobs:
  validate_and_publish:
    name: Validate and Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Yarn
        if: ${{ env.ACT }}
        run: npm install yarn -g

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Symlink Local Dependencies
        run: yarn lerna bootstrap

      - name: Build, Lint, Test
        run: yarn run validate

      - name: Pubish Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn lerna publish --yes
